### PR TITLE
Change target to reflect a previous makefile change

### PR DESCRIPTION
**Pull request by joelostblom**
I believe this is the reason why travis is failing, not sure how important it is for us but let's see if this fixes it https://github.com/merely-useful/py-rse/commit/41398d6c42fa77360276a2c4d69e5c26ff2fcd07#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L58-L59

### CODE REVIEW

**Comment by gvwilson** [comment]
Looks good to me - @lwjohnst86 can you please check as well?

**Comment by DamienIrving** [comment]
The checks failed on this PR (https://travis-ci.org/github/merely-useful/py-rse/builds/748866655), does that mean it isn't fixed?

**Comment by joelostblom** [comment]
The previous error is fixed, we're running into a new one now. Travis' pandoc seem to be complaining that `--metadata-file` is not a valid option but it certainly is (unless that pandoc version is ancient maybe?). The pandoc command is autogenerated by our RMarkdown command in the makefile, not sure if that matters. I could not find anything on the pandoc issue tracker so suspecting that the error lies elsewhere and this is a side effect.

**Comment by lwjohnst86** [comment]
Sorry guys, thought I got rid of the travis file. We're using GitHub Actions to build the website, not Travis. Closing

**Pull request closed without merging**
