### PR TITLE
Adding basic web site statistics using plausible.io.

### PR DESCRIPTION
**Pull request by gvwilson**
https://plausible.io/ offers an ethical approach to collecting web traffic statistics. This addition will let us count the number of people visiting https://merely-useful.tech/ (we can then drill down to the py-rse book or others). I'm assuming that once this is merged, all of the HTML pages will be updated...

### CODE REVIEW

**Review by joelostblom — APPROVED** [review]
Yay for a considerate alternative to Google analytics!

**Comment by k8hertweck** [comment]
I just added Plausible tracking to another project built in Jekyll, and it required a few lines be added to the config file.

I found [this bookdown project](https://github.com/oscarbaruffa/BigBookofR) that uses Plausible and seems to only include the code snippet in the header (as you've done), so fingers crossed we're good to go.

**Comment by gvwilson** [comment]
@k8hertweck can you please point us at the config or summarize here? I _think_ adding to the include file will be enough, but as a backup...

**Comment by k8hertweck** [comment]
@gvwilson That's the thing! I don't see any other place the config is necessary for a site rendered via bookdown. There isn't one in the link I shared (only the code snippet in the header).

**Comment by lwjohnst86** [comment]
Let's try it out then! Merging and @gvwilson you can watch to see how it goes, if it works.

**Pull request merged**
